"""empty message

Revision ID: 16ae3c9ac9e6
Revises: 8a0ee0cd9b5d
Create Date: 2023-04-18 15:05:00.453379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ae3c9ac9e6'
down_revision = '8a0ee0cd9b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine', sa.String(length=50), nullable=False))
        batch_op.drop_column('cuisine_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('cuisine')

    # ### end Alembic commands ###
