"""empty message

Revision ID: 1899b0ea89cf
Revises: 16ae3c9ac9e6
Create Date: 2023-04-19 09:52:03.737398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1899b0ea89cf'
down_revision = '16ae3c9ac9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom1', sa.String(length=100), nullable=False),
    sa.Column('symptom2', sa.String(length=100), nullable=False),
    sa.Column('symptom3', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptom')
    # ### end Alembic commands ###
